version: '3.0'
services:
  web:
    image: gaetancollaud/cocktail-backend
    container_name: cockail-backend
    build: .
    ports:
      - 8080:8080
    links:
      - mongodb:mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  mongodb:
    image: mongo
    container_name: cocktail-mongo
    user: root
    ports:
      - 27017:27017
    volumes:
      - "./data/mongo:/data/db"
